apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
annotations:
  "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: init
        image: rtsp/mongosh
        env:
        - name: ATLAS_URI
          valueFrom:
            secretKeyRef:
              name: atlas-uri-secret
              key: ATLAS_URI
        - name: MONGODB_LOCAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: local-mongodb-password
              key: MONGODB_LOCAL_PASSWORD
        command: ["bash"]
        args:
        - -c
        - |
          echo "Pass"
          # # dump
          # mongodump -vvvvv --uri "$ATLAS_URI" --db "sample_training" --collection "posts" --archive > db.dump

          # # load
          # export PRIMARY_HOST=$(mongosh "mongodb://my-user:$MONGODB_LOCAL_PASSWORD@devops-mongodb-svc.mongodb.svc.cluster.local:40333" --quiet --eval "rs.status()" --json | jq -r '.members[] | select(.stateStr == "PRIMARY") | .name' | cut -d':' -f1)
          # echo "Primary Host : $PRIMARY_HOST"

          # # restore
          # mongorestore --uri "mongodb://my-user:$MONGODB_LOCAL_PASSWORD@$PRIMARY_HOST:40333" --archive < db.dump      
      containers:
      - name: main
        image: {{ .Values.mainContainer.image }}:{{ .Values.mainContainer.tag }}
        env:
          {{- toYaml .Values.env | nindent 12 }}
        command: ["python", "main.py"]
  backoffLimit: 1