apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: init-load-data
        image: rtsp/mongosh
        env:
        - name: ATLAS_URI
          valueFrom:
            secretKeyRef:
              name: atlas-uri-secret
              key: ATLAS_URI
        - name: MONGODB_LOCAL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: local-mongodb-password
              key: MONGODB_LOCAL_PASSWORD
        command: ["bash"]
        args:
        - -c
        - |
          # dump
          mongodump --uri "$ATLAS_URI" --db "sample_training" --collection "posts" --archive > db.dump

          # load
          export PRIMARY_HOST=$(mongosh "mongodb://my-user:$MONGODB_LOCAL_PASSWORD@devops-mongodb-svc.mongodb.svc.cluster.local:40333" --quiet --eval "rs.status()" --json | jq -r '.members[] | select(.stateStr == "PRIMARY") | .name' | cut -d':' -f1)
          echo "Primary Host : $PRIMARY_HOST"

          # restore
          mongorestore --uri "mongodb://my-user:$MONGODB_LOCAL_PASSWORD@$PRIMARY_HOST:40333" --archive < db.dump      
      containers:
      - name: main
        image: {{ .Values.mainContainer.image }}:{{ .Values.mainContainer.tag }}
        command: ["python", "main.py"]
  backoffLimit: 1