image:
  repository: nadavdev/dropit-app-fe
  pullPolicy: IfNotPresent
  tag: "main"

replicaCount: 2

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: posts-app.dropit.com
      paths:
        - path: /
          pathType: ImplementationSpecific


env:
  - name: REACT_APP_OPENSSL_LEGACY_PROVIDER 
    value: "false"