name: CI/CD to Local Kind Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy-to-kind:
    runs-on: self-hosted  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: View Work Dir 
        run: |
          pwd
          ls -la

      - name: View current-context
        run: |
          k config current-context