name: MongoDB Dump AND Sync K8s Job

on:
    workflow_dispatch:

jobs:
  mongodb-dump-data:
    runs-on: self-hosted 
    env:
      ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION: node16
      ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION: node16

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean up old job
        run: kubectl delete job dump-sync-job -n mongodb --ignore-not-found
      
      - name: Deploy Job
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
        run: |
          MONGODB_LOCAL_PASSWORD=$(kubectl get secrets -n mongodb my-user-password -o json | jq -r '.data | with_entries(.value |= @base64d) | .password')
          helm upgrade --install dump-sync-job mongodb-configuration/dump-sync-job-helm --set atlas.uri=$ATLAS_URI --set local.password=$MONGODB_LOCAL_PASSWORD -n mongodb

