name: MongoDB Dump K8s Job

on:
    workflow_dispatch:

jobs:
  create-cluster:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Job
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
        run: |
          helm upgrade --install dump-job mongodb-configuration/dump-job --set atlas.uri=$(echo -n "$ATLAS_URI" | base64) -n mongodb

