name: MongoDB Dump K8s Job

on:
    workflow_dispatch:

jobs:
  mongodb-dump-data:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean up old job
        run: kubectl delete job mongodb-dump-data-job -n mongodb --ignore-not-found
      
      - name: Deploy Job
        env:
          ATLAS_URI: ${{ secrets.ATLAS_URI }}
        run: |
          MONGODB_LOCAL_PASSWORD=$(kubectl get secrets -n mongodb my-user-password -o json | jq -r '.data | with_entries(.value |= @base64d) | .password')
          helm upgrade --install dump-job mongodb-configuration/dump-job --set atlas.uri=$ATLAS_URI --set local.password=$MONGODB_LOCAL_PASSWORD -n mongodb

